/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Alexia
 */
public class JF_AdminOptions extends javax.swing.JFrame {

    /**
     * Creates new form JF_AdminOptions
     */
    public JF_AdminOptions() {
        initComponents();
        //setButtonImages();
        this.setLocationRelativeTo(this);
    }
    
    private void setButtonImages(){
        setImageButton(btnAdmiCatalogos, "src/Images/adminCatalogs.png");
        setImageButton(btnAdmiNoticias, "src/Images/adminNews.png");
        setImageButton(btnAdmiPersonas, "src/Images/adminPerson.png");
        setImageButton(btnPartidos, "src/Images/adminMatches.png");
        setImageButton(btnAdmiBitacora, "src/Images/adminLog.png");
        setImageButton(btnAdmiParametros, "src/Images/adminParameters.png");
        setImageButton(btnOther, "src/Images/adminOther.png");
    }
    
    private void setImageButton(JButton buttonName, String imageDirectory){
        ImageIcon image = new ImageIcon(imageDirectory);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(buttonName.getWidth(), buttonName.getHeight(), Image.SCALE_DEFAULT));
        buttonName.setIcon(icon);
        this.repaint();
    }
    
    //GETTERS AND SETTERS

    public JButton getBtnBack() {
        return btnBack;
    }

    public JButton getBtnAdmiNoticias() {
        return btnAdmiNoticias;
    }

    public JButton getBtnAdmiPersonas() {
        return btnAdmiPersonas;
    }

    public JButton getBtnAdmiCatalogos() {
        return btnAdmiCatalogos;
    }

    public JButton getBtnBitacora() {
        return btnAdmiBitacora;
    }

    public JButton getBtnEstadisticas() {
        return btnPartidos;
    }

    public JButton getBtnAdmiParametros() {
        return btnAdmiParametros;
    }

    public JButton getBtnPartidos() {
        return btnPartidos;
    }

    public JButton getBtnAdmiOther() {
        return btnOther;
    }

    public void setBtnOther(JButton btnOther) {
        this.btnOther = btnOther;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btnAdmiNoticias = new javax.swing.JButton();
        btnAdmiCatalogos = new javax.swing.JButton();
        btnPartidos = new javax.swing.JButton();
        btnAdmiParametros = new javax.swing.JButton();
        btnAdmiPersonas = new javax.swing.JButton();
        btnAdmiBitacora = new javax.swing.JButton();
        lblAdminOpciones = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnOther = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(86, 4, 44));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        jPanel1.add(lblLogo);
        lblLogo.setBounds(1066, 6, 200, 125);

        btnAdmiNoticias.setBackground(new java.awt.Color(255, 204, 102));
        btnAdmiNoticias.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        btnAdmiNoticias.setText("Administrar Noticias");
        btnAdmiNoticias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmiNoticiasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmiNoticias);
        btnAdmiNoticias.setBounds(490, 160, 300, 159);

        btnAdmiCatalogos.setBackground(new java.awt.Color(255, 204, 102));
        btnAdmiCatalogos.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        btnAdmiCatalogos.setText("Administrar Catálogos");
        btnAdmiCatalogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmiCatalogosActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmiCatalogos);
        btnAdmiCatalogos.setBounds(170, 160, 299, 159);

        btnPartidos.setBackground(new java.awt.Color(255, 204, 102));
        btnPartidos.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        btnPartidos.setText("Administrar Partidos");
        btnPartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartidosActionPerformed(evt);
            }
        });
        jPanel1.add(btnPartidos);
        btnPartidos.setBounds(170, 340, 299, 159);

        btnAdmiParametros.setBackground(new java.awt.Color(255, 204, 102));
        btnAdmiParametros.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        btnAdmiParametros.setText("Administrar Parámetros");
        btnAdmiParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmiParametrosActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmiParametros);
        btnAdmiParametros.setBounds(810, 340, 299, 159);

        btnAdmiPersonas.setBackground(new java.awt.Color(255, 204, 102));
        btnAdmiPersonas.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        btnAdmiPersonas.setText("Administrar Personas");
        btnAdmiPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmiPersonasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmiPersonas);
        btnAdmiPersonas.setBounds(810, 160, 299, 159);

        btnAdmiBitacora.setBackground(new java.awt.Color(255, 204, 102));
        btnAdmiBitacora.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        btnAdmiBitacora.setText("Administrar Bitácora");
        btnAdmiBitacora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmiBitacoraActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmiBitacora);
        btnAdmiBitacora.setBounds(490, 340, 300, 159);

        lblAdminOpciones.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        lblAdminOpciones.setForeground(new java.awt.Color(255, 255, 255));
        lblAdminOpciones.setText("Opciones de Administrador");
        jPanel1.add(lblAdminOpciones);
        lblAdminOpciones.setBounds(111, 42, 521, 48);

        btnBack.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        btnBack.setContentAreaFilled(false);
        btnBack.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backPressed.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(47, 50, 46, 40);

        btnOther.setBackground(new java.awt.Color(255, 204, 102));
        btnOther.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        btnOther.setText("Administrar Eventos, Estadios y Equipos");
        btnOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtherActionPerformed(evt);
            }
        });
        jPanel1.add(btnOther);
        btnOther.setBounds(350, 520, 594, 166);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdmiParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmiParametrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdmiParametrosActionPerformed

    private void btnPartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartidosActionPerformed
        
    }//GEN-LAST:event_btnPartidosActionPerformed

    private void btnAdmiCatalogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmiCatalogosActionPerformed

    }//GEN-LAST:event_btnAdmiCatalogosActionPerformed

    private void btnAdmiNoticiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmiNoticiasActionPerformed

    }//GEN-LAST:event_btnAdmiNoticiasActionPerformed

    private void btnAdmiPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmiPersonasActionPerformed

    }//GEN-LAST:event_btnAdmiPersonasActionPerformed

    private void btnAdmiBitacoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmiBitacoraActionPerformed

    }//GEN-LAST:event_btnAdmiBitacoraActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOtherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmiBitacora;
    private javax.swing.JButton btnAdmiCatalogos;
    private javax.swing.JButton btnAdmiNoticias;
    private javax.swing.JButton btnAdmiParametros;
    private javax.swing.JButton btnAdmiPersonas;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnOther;
    private javax.swing.JButton btnPartidos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdminOpciones;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
