/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Alexia
 */
public class JF_AdminMatchStats extends javax.swing.JFrame {

    /**
     * Creates new form JF_AdminMatchStats
     */
    public JF_AdminMatchStats() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        lblAdminPartidos = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        cmbPartido = new javax.swing.JComboBox<>();
        txtAmarillas = new javax.swing.JTextField();
        lblPartido1 = new javax.swing.JLabel();
        lblPartido2 = new javax.swing.JLabel();
        txtAmarillas1 = new javax.swing.JTextField();
        lblPartido3 = new javax.swing.JLabel();
        txtAmarillas2 = new javax.swing.JTextField();
        lblPartido4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(86, 4, 44));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        btnBack.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        btnBack.setContentAreaFilled(false);
        btnBack.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backPressed.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(38, 50, 46, 40);

        lblAdminPartidos.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        lblAdminPartidos.setForeground(new java.awt.Color(255, 255, 255));
        lblAdminPartidos.setText("Administrar Estadísticas Partido");
        jPanel1.add(lblAdminPartidos);
        lblAdminPartidos.setBounds(102, 42, 521, 48);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        jPanel1.add(lblLogo);
        lblLogo.setBounds(1057, 6, 200, 125);

        cmbPartido.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbPartido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbPartido);
        cmbPartido.setBounds(320, 160, 240, 40);

        txtAmarillas.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jPanel1.add(txtAmarillas);
        txtAmarillas.setBounds(360, 420, 120, 40);

        lblPartido1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblPartido1.setForeground(new java.awt.Color(255, 255, 255));
        lblPartido1.setText("Elija un partido:");
        jPanel1.add(lblPartido1);
        lblPartido1.setBounds(120, 160, 190, 40);

        lblPartido2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblPartido2.setForeground(new java.awt.Color(255, 255, 255));
        lblPartido2.setText("Tarjetas Amarillas");
        jPanel1.add(lblPartido2);
        lblPartido2.setBounds(150, 280, 190, 40);

        txtAmarillas1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jPanel1.add(txtAmarillas1);
        txtAmarillas1.setBounds(360, 280, 120, 40);

        lblPartido3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblPartido3.setForeground(new java.awt.Color(255, 255, 255));
        lblPartido3.setText("Tarjetas Rojas");
        jPanel1.add(lblPartido3);
        lblPartido3.setBounds(150, 350, 190, 40);

        txtAmarillas2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jPanel1.add(txtAmarillas2);
        txtAmarillas2.setBounds(360, 350, 120, 40);

        lblPartido4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblPartido4.setForeground(new java.awt.Color(255, 255, 255));
        lblPartido4.setText("Tiros de esquina");
        jPanel1.add(lblPartido4);
        lblPartido4.setBounds(150, 420, 190, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_AdminMatchStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_AdminMatchStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_AdminMatchStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_AdminMatchStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_AdminMatchStats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbPartido;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdminPartidos;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPartido1;
    private javax.swing.JLabel lblPartido2;
    private javax.swing.JLabel lblPartido3;
    private javax.swing.JLabel lblPartido4;
    private javax.swing.JTextField txtAmarillas;
    private javax.swing.JTextField txtAmarillas1;
    private javax.swing.JTextField txtAmarillas2;
    // End of variables declaration//GEN-END:variables
}
