/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexia
 */
public class JF_AdminNews extends javax.swing.JFrame {

    /**
     * Creates new form JF_AdminNoticias
     */
    public JF_AdminNews() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupAdmiNoticias = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        lblAdminNoticias = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        rbtnAgregar = new javax.swing.JRadioButton();
        rbtnEditar = new javax.swing.JRadioButton();
        rbtnEliminar = new javax.swing.JRadioButton();
        cmbEstado = new javax.swing.JComboBox<>();
        lblTipo = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        lblTitulo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lblTexto = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        btnCargarImagen = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNoticias = new javax.swing.JTable();
        lblEstado = new javax.swing.JLabel();
        txtareaEliminar = new javax.swing.JTextArea();
        txtTexto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(86, 4, 44));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        btnBack.setBackground(new java.awt.Color(86, 4, 44));
        btnBack.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        btnBack.setContentAreaFilled(false);
        btnBack.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backPressed.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(47, 47, 46, 40);

        lblAdminNoticias.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        lblAdminNoticias.setForeground(new java.awt.Color(255, 255, 255));
        lblAdminNoticias.setText("Administrar Noticias");
        jPanel1.add(lblAdminNoticias);
        lblAdminNoticias.setBounds(111, 39, 521, 48);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        jPanel1.add(lblLogo);
        lblLogo.setBounds(1050, 16, 200, 125);

        rbtnAgregar.setBackground(new java.awt.Color(86, 4, 44));
        btnGroupAdmiNoticias.add(rbtnAgregar);
        rbtnAgregar.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        rbtnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        rbtnAgregar.setText("Agregar");
        rbtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnAgregar);
        rbtnAgregar.setBounds(720, 160, 150, 37);
        rbtnAgregar.setSelected(true);

        rbtnEditar.setBackground(new java.awt.Color(86, 4, 44));
        btnGroupAdmiNoticias.add(rbtnEditar);
        rbtnEditar.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        rbtnEditar.setForeground(new java.awt.Color(255, 255, 255));
        rbtnEditar.setText("Editar");
        rbtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnEditar);
        rbtnEditar.setBounds(910, 160, 100, 37);

        rbtnEliminar.setBackground(new java.awt.Color(86, 4, 44));
        btnGroupAdmiNoticias.add(rbtnEliminar);
        rbtnEliminar.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        rbtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        rbtnEliminar.setText("Eliminar");
        rbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnEliminar);
        rbtnEliminar.setBounds(1060, 160, 150, 37);

        cmbEstado.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2" }));
        jPanel1.add(cmbEstado);
        cmbEstado.setBounds(790, 230, 190, 30);

        lblTipo.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(255, 255, 255));
        lblTipo.setText("Tipo:");
        jPanel1.add(lblTipo);
        lblTipo.setBounds(1010, 220, 60, 40);

        cmbTipo.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2" }));
        jPanel1.add(cmbTipo);
        cmbTipo.setBounds(1060, 230, 190, 30);

        lblTitulo.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Título:");
        jPanel1.add(lblTitulo);
        lblTitulo.setBounds(720, 280, 60, 30);

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtTitulo);
        txtTitulo.setBounds(790, 280, 410, 30);

        lblTexto.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblTexto.setForeground(new java.awt.Color(255, 255, 255));
        lblTexto.setText("Texto:");
        jPanel1.add(lblTexto);
        lblTexto.setBounds(720, 340, 120, 25);

        lblFoto.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblFoto.setForeground(new java.awt.Color(255, 255, 255));
        lblFoto.setText("Foto:");
        jPanel1.add(lblFoto);
        lblFoto.setBounds(990, 340, 70, 30);

        btnCargarImagen.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnCargarImagen.setText("Cargar foto");
        btnCargarImagen.setAlignmentY(0.0F);
        jPanel1.add(btnCargarImagen);
        btnCargarImagen.setBounds(1060, 340, 120, 30);

        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/avatar.png"))); // NOI18N
        lblImagen.setAlignmentX(0.5F);
        lblImagen.setMaximumSize(new java.awt.Dimension(180, 230));
        lblImagen.setMinimumSize(new java.awt.Dimension(180, 230));
        lblImagen.setPreferredSize(new java.awt.Dimension(180, 230));
        jPanel1.add(lblImagen);
        lblImagen.setBounds(1010, 380, 180, 230);

        btnAceptar.setBackground(new java.awt.Color(86, 4, 44));
        btnAceptar.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorderPainted(false);
        jPanel1.add(btnAceptar);
        btnAceptar.setBounds(920, 630, 130, 40);

        tblNoticias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Estado", "Título", "Vistas", "Fecha Publicación", "Tipo", "Rating"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNoticias.setIntercellSpacing(new java.awt.Dimension(3, 3));
        tblNoticias.setShowGrid(true);
        tblNoticias.getTableHeader().setResizingAllowed(false);
        tblNoticias.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblNoticias);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 160, 616, 480);

        lblEstado.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(255, 255, 255));
        lblEstado.setText("Estado:");
        jPanel1.add(lblEstado);
        lblEstado.setBounds(720, 220, 120, 40);

        txtareaEliminar.setBackground(new java.awt.Color(86, 4, 44));
        txtareaEliminar.setColumns(20);
        txtareaEliminar.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        txtareaEliminar.setForeground(new java.awt.Color(255, 255, 255));
        txtareaEliminar.setRows(3);
        txtareaEliminar.setText("Seleccione una noticia de la tabla de \nla izquierda para eliminarla. Presione  \n     aceptar para concluir la acción.");
        txtareaEliminar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(82, 4, 44)));
        txtareaEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtareaEliminar.setDisabledTextColor(new java.awt.Color(82, 4, 44));
        jPanel1.add(txtareaEliminar);
        txtareaEliminar.setBounds(720, 330, 500, 150);
        txtareaEliminar.setEditable(false);
        txtareaEliminar.setVisible(false);

        txtTexto.setColumns(20);
        txtTexto.setLineWrap(true);
        txtTexto.setRows(5);
        jPanel1.add(txtTexto);
        txtTexto.setBounds(720, 380, 232, 230);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JComboBox<String> getCmbEstado() {
        return cmbEstado;
    }

    public void setCmbEstado(JComboBox<String> cmbEstado) {
        this.cmbEstado = cmbEstado;
    }

    public JComboBox<String> getCmbTipo() {
        return cmbTipo;
    }

    public void setCmbTipo(JComboBox<String> cmbTipo) {
        this.cmbTipo = cmbTipo;
    }

    public JLabel getLblImagen() {
        return lblImagen;
    }

    public void setLblImagen(JLabel lblImagen) {
        this.lblImagen = lblImagen;
    }

    public JTable getTblNoticias() {
        return tblNoticias;
    }

    public void setTblNoticias(JTable tblNoticias) {
        this.tblNoticias = tblNoticias;
    }

    public JTextArea getTxtTexto() {
        return txtTexto;
    }

    public void setTxtTexto(JTextArea txtTexto) {
        this.txtTexto = txtTexto;
    }

    public JTextField getTxtTitulo() {
        return txtTitulo;
    }

    public void setTxtTitulo(JTextField txtTitulo) {
        this.txtTitulo = txtTitulo;
    }

    public JTextArea getTxtareaEliminar() {
        return txtareaEliminar;
    }

    public void setTxtareaEliminar(JTextArea txtareaEliminar) {
        this.txtareaEliminar = txtareaEliminar;
    }

    public JButton getBtnAceptar() {
        return btnAceptar;
    }

    public void setBtnAceptar(JButton btnAceptar) {
        this.btnAceptar = btnAceptar;
    }

    public JButton getBtnBack() {
        return btnBack;
    }

    public void setBtnBack(JButton btnBack) {
        this.btnBack = btnBack;
    }

    public JButton getBtnCargarImagen() {
        return btnCargarImagen;
    }

    public void setBtnCargarImagen(JButton btnCargarImagen) {
        this.btnCargarImagen = btnCargarImagen;
    }

    public JRadioButton getRbtnAgregar() {
        return rbtnAgregar;
    }

    public void setRbtnAgregar(JRadioButton rbtnAgregar) {
        this.rbtnAgregar = rbtnAgregar;
    }

    public JRadioButton getRbtnEditar() {
        return rbtnEditar;
    }

    public void setRbtnEditar(JRadioButton rbtnEditar) {
        this.rbtnEditar = rbtnEditar;
    }

    public JRadioButton getRbtnEliminar() {
        return rbtnEliminar;
    }

    public void setRbtnEliminar(JRadioButton rbtnEliminar) {
        this.rbtnEliminar = rbtnEliminar;
    }
    
    

    public void esconderMostrarTodo(boolean flag){
        lblEstado.setVisible(flag);
        cmbTipo.setVisible(flag);
        lblTipo.setVisible(flag);
        cmbEstado.setVisible(flag);
        lblTitulo.setVisible(flag);
        txtTitulo.setVisible(flag);
        lblTexto.setVisible(flag);
        txtTexto.setVisible(flag);
        lblFoto.setVisible(flag);
        lblImagen.setVisible(flag);
        btnCargarImagen.setVisible(flag);
        txtareaEliminar.setVisible(!flag);
    }
    
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void rbtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAgregarActionPerformed
        esconderMostrarTodo(true);
    }//GEN-LAST:event_rbtnAgregarActionPerformed

    private void rbtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEditarActionPerformed
        esconderMostrarTodo(true);
    }//GEN-LAST:event_rbtnEditarActionPerformed

    private void rbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEliminarActionPerformed
        esconderMostrarTodo(false);
    }//GEN-LAST:event_rbtnEliminarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCargarImagen;
    private javax.swing.ButtonGroup btnGroupAdmiNoticias;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdminNoticias;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbtnAgregar;
    private javax.swing.JRadioButton rbtnEditar;
    private javax.swing.JRadioButton rbtnEliminar;
    private javax.swing.JTable tblNoticias;
    private javax.swing.JTextArea txtTexto;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextArea txtareaEliminar;
    // End of variables declaration//GEN-END:variables
}
