/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextField;

/**
 *
 * @author Alexia
 */
public class JF_AdminCatalogs extends javax.swing.JFrame {

    /**
     * Creates new form JF_AdminCatalogos
     */
    public JF_AdminCatalogs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbCatalogo = new javax.swing.JComboBox<>();
        btnAceptar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtAgregar = new javax.swing.JTextField();
        lblOpciones = new javax.swing.JLabel();
        txtModificar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstOpciones = new javax.swing.JList<>();
        btnBack = new javax.swing.JButton();
        lblCatalogo1 = new javax.swing.JLabel();
        lblAgregar = new javax.swing.JLabel();
        btnAgregar1 = new javax.swing.JButton();
        cmbSeleccionar = new javax.swing.JComboBox<>();
        lblSeleccionar = new javax.swing.JLabel();
        lblModificar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(86, 4, 44));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(1065, 6, 200, 125);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Administrar Catálogos");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(126, 66, 445, 48);

        cmbCatalogo.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        cmbCatalogo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un catálogo", "Tipo de Identificación", "Género", "Posición", "País", "Provincia", "Cantón", "Distrito", "Estado de Noticia", "Tipo de Noticia" }));
        cmbCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCatalogoActionPerformed(evt);
            }
        });
        jPanel1.add(cmbCatalogo);
        cmbCatalogo.setBounds(263, 214, 346, 38);

        btnAceptar.setBackground(new java.awt.Color(0, 153, 0));
        btnAceptar.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        jPanel1.add(btnAceptar);
        btnAceptar.setBounds(330, 660, 196, 39);
        btnAceptar.setVisible(false);

        btnModificar.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        btnModificar.setText("Modificar");
        jPanel1.add(btnModificar);
        btnModificar.setBounds(470, 480, 196, 39);

        btnEliminar.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar);
        btnEliminar.setBounds(810, 660, 360, 39);

        txtAgregar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtAgregar);
        txtAgregar.setBounds(180, 360, 260, 40);

        lblOpciones.setFont(new java.awt.Font("Yu Gothic UI", 0, 23)); // NOI18N
        lblOpciones.setForeground(new java.awt.Color(255, 255, 255));
        lblOpciones.setText("Lista Catálogo");
        jPanel1.add(lblOpciones);
        lblOpciones.setBounds(806, 201, 367, 47);

        txtModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtModificar);
        txtModificar.setBounds(180, 480, 260, 40);

        lstOpciones.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lstOpciones.setFixedCellHeight(30);
        lstOpciones.setFixedCellWidth(5);
        jScrollPane1.setViewportView(lstOpciones);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(806, 260, 367, 383);

        btnBack.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        btnBack.setContentAreaFilled(false);
        btnBack.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backPressed.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(62, 74, 46, 40);

        lblCatalogo1.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        lblCatalogo1.setForeground(new java.awt.Color(255, 255, 255));
        lblCatalogo1.setText("Catálogo");
        jPanel1.add(lblCatalogo1);
        lblCatalogo1.setBounds(113, 217, 144, 32);

        lblAgregar.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAgregar.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregar.setText("Agregar ");
        jPanel1.add(lblAgregar);
        lblAgregar.setBounds(180, 330, 260, 25);

        btnAgregar1.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        btnAgregar1.setText("Agregar");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar1);
        btnAgregar1.setBounds(470, 360, 196, 39);

        cmbSeleccionar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbSeleccionar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbSeleccionar);
        cmbSeleccionar.setBounds(440, 560, 220, 40);
        cmbSeleccionar.setVisible(false);

        lblSeleccionar.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        lblSeleccionar.setForeground(new java.awt.Color(255, 255, 255));
        lblSeleccionar.setText("Seleccione");
        jPanel1.add(lblSeleccionar);
        lblSeleccionar.setBounds(180, 560, 250, 27);
        lblSeleccionar.setVisible(false);

        lblModificar.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblModificar.setForeground(new java.awt.Color(255, 255, 255));
        lblModificar.setText("Modificar");
        jPanel1.add(lblModificar);
        lblModificar.setBounds(180, 450, 260, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getCmbCatalogo() {
        return cmbCatalogo.getSelectedItem().toString();
    }

    public void setCmbCatalogo(JComboBox<String> cmbCatalogo) {
        this.cmbCatalogo = cmbCatalogo;
    }

    public String getTextAgregar() {
        return txtAgregar.getText();
    }

    public void setTextAgregar(String text) {
        this.txtAgregar.setText(text);
    }

    public String getTextModificar() {
        return txtModificar.getText();
    }

    public void setjTextField3(String text) {
        this.txtModificar.setText(text);
    }

    public JList<String> getLstOpciones() {
        return lstOpciones;
    }

    public void setLstOpciones(JList<String> lstOpciones) {
        this.lstOpciones = lstOpciones;
    }
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // validar si de verdad desea eliminar el item seleccionado de la lista
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        JF_AdminOptions adminOptions = new JF_AdminOptions();
        adminOptions.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void dissapearOptions(boolean flag){
        lblSeleccionar.setVisible(flag);
        cmbSeleccionar.setVisible(flag);
        btnAceptar.setVisible(flag);
    }
    
    private void cmbCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCatalogoActionPerformed
        lblOpciones.setText("Catálogo ");
        lblAgregar.setText("Agregar ");
        lblModificar.setText("Modificar ");
        String catalog = getCmbCatalogo();
        
        
        if(!"Seleccione un catálogo".equals(catalog)){
            lblOpciones.setText(lblOpciones.getText() + "" + catalog);
            lblAgregar.setText(lblAgregar.getText() + "" + catalog);
            lblModificar.setText(lblModificar.getText() + "" + catalog);
        }
        
        if("Provincia".equals(catalog)){
            lblSeleccionar.setText("Selecione un Pais");
            //cmb de seleccionar paises
        }
        
        if("Cantón".equals(catalog)){
            lblSeleccionar.setText("Selecione una Provincia");
            //cmb de seleccionar provincias
        }
        
        if("Distrito".equals(catalog)){
            lblSeleccionar.setText("Selecione un Cantón");
            //cmb de seleccionar cantones
        }
        
        dissapearOptions(false);
    }//GEN-LAST:event_cmbCatalogoActionPerformed

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        String catalog = getCmbCatalogo();
        if (catalog == "Distrito" || catalog == "Provincia" || catalog == "Cantón"){
            dissapearOptions(true);
        }
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_AdminCatalogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_AdminCatalogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_AdminCatalogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_AdminCatalogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_AdminCatalogs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbCatalogo;
    private javax.swing.JComboBox<String> cmbSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblCatalogo1;
    private javax.swing.JLabel lblModificar;
    private javax.swing.JLabel lblOpciones;
    private javax.swing.JLabel lblSeleccionar;
    private javax.swing.JList<String> lstOpciones;
    private javax.swing.JTextField txtAgregar;
    private javax.swing.JTextField txtModificar;
    // End of variables declaration//GEN-END:variables
}
