/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JFormattedTextField;

/**
 *
 * @author Alexia
 */
public class JF_AdminMatches extends javax.swing.JFrame {

    /**
     * Creates new form JF_AdminMatches
     */
    public JF_AdminMatches() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        lblAdminPartidos = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        btnCrearPartidos = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        lblNumCamisa = new javax.swing.JLabel();
        lblPartido = new javax.swing.JLabel();
        lblTeam1 = new javax.swing.JLabel();
        cmbPartido = new javax.swing.JComboBox<>();
        cmbTeam1 = new javax.swing.JComboBox<>();
        txtDateHour = new javax.swing.JFormattedTextField();
        lblTeam2 = new javax.swing.JLabel();
        lblNumCamisa1 = new javax.swing.JLabel();
        cmbTeam3 = new javax.swing.JComboBox<>();
        btnCrearGrupos = new javax.swing.JButton();
        cmbTeam4 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(86, 4, 44));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        btnBack.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        btnBack.setContentAreaFilled(false);
        btnBack.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backPressed.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(38, 50, 46, 40);

        lblAdminPartidos.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        lblAdminPartidos.setForeground(new java.awt.Color(255, 255, 255));
        lblAdminPartidos.setText("Administrar Partidos");
        jPanel1.add(lblAdminPartidos);
        lblAdminPartidos.setBounds(102, 42, 521, 48);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        jPanel1.add(lblLogo);
        lblLogo.setBounds(1057, 6, 200, 125);

        btnCrearPartidos.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnCrearPartidos.setText("Crear partidos");
        btnCrearPartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPartidosActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearPartidos);
        btnCrearPartidos.setBounds(770, 610, 190, 40);

        btnAceptar.setBackground(new java.awt.Color(0, 153, 0));
        btnAceptar.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar);
        btnAceptar.setBounds(530, 610, 200, 39);

        lblNumCamisa.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblNumCamisa.setForeground(new java.awt.Color(255, 255, 255));
        lblNumCamisa.setText("Estadio");
        jPanel1.add(lblNumCamisa);
        lblNumCamisa.setBounds(230, 290, 150, 40);

        lblPartido.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblPartido.setForeground(new java.awt.Color(255, 255, 255));
        lblPartido.setText("Partido");
        jPanel1.add(lblPartido);
        lblPartido.setBounds(230, 210, 150, 40);

        lblTeam1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblTeam1.setForeground(new java.awt.Color(255, 255, 255));
        lblTeam1.setText("Team 1");
        jPanel1.add(lblTeam1);
        lblTeam1.setBounds(660, 210, 150, 40);

        cmbPartido.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbPartido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbPartido);
        cmbPartido.setBounds(350, 210, 240, 40);

        cmbTeam1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbTeam1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbTeam1);
        cmbTeam1.setBounds(350, 290, 240, 40);

        txtDateHour.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yy h:m aa"))));
        txtDateHour.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtDateHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateHourActionPerformed(evt);
            }
        });
        jPanel1.add(txtDateHour);
        txtDateHour.setBounds(540, 420, 190, 40);

        lblTeam2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblTeam2.setForeground(new java.awt.Color(255, 255, 255));
        lblTeam2.setText("Team 2");
        jPanel1.add(lblTeam2);
        lblTeam2.setBounds(660, 290, 150, 40);

        lblNumCamisa1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblNumCamisa1.setForeground(new java.awt.Color(255, 255, 255));
        lblNumCamisa1.setText("Fecha y hora");
        jPanel1.add(lblNumCamisa1);
        lblNumCamisa1.setBounds(560, 370, 150, 40);

        cmbTeam3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbTeam3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbTeam3);
        cmbTeam3.setBounds(790, 210, 240, 40);

        btnCrearGrupos.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnCrearGrupos.setText("Crear grupos");
        jPanel1.add(btnCrearGrupos);
        btnCrearGrupos.setBounds(290, 610, 190, 40);

        cmbTeam4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbTeam4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbTeam4);
        cmbTeam4.setBounds(790, 290, 240, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JFormattedTextField getTxtDateHour() {
        return txtDateHour;
    }
    
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtDateHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateHourActionPerformed

    private void btnCrearPartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPartidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearPartidosActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_AdminMatches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_AdminMatches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_AdminMatches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_AdminMatches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_AdminMatches().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCrearGrupos;
    private javax.swing.JButton btnCrearPartidos;
    private javax.swing.JComboBox<String> cmbPartido;
    private javax.swing.JComboBox<String> cmbTeam1;
    private javax.swing.JComboBox<String> cmbTeam3;
    private javax.swing.JComboBox<String> cmbTeam4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdminPartidos;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNumCamisa;
    private javax.swing.JLabel lblNumCamisa1;
    private javax.swing.JLabel lblPartido;
    private javax.swing.JLabel lblTeam1;
    private javax.swing.JLabel lblTeam2;
    private javax.swing.JFormattedTextField txtDateHour;
    // End of variables declaration//GEN-END:variables
}
