/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Alexia
 */
public class JF_AdminPerson extends javax.swing.JFrame {

    /**
     * Creates new form JF_AdminNews
     */
    public JF_AdminPerson() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupAdmiPersonas = new javax.swing.ButtonGroup();
        pnlAdminPersonas = new javax.swing.JPanel();
        lblAdmiPersonas = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        cmbPersona = new javax.swing.JComboBox<>();
        lblPersona = new javax.swing.JLabel();
        rbtnEditar = new javax.swing.JRadioButton();
        rbtnAgregar = new javax.swing.JRadioButton();
        rbtnEliminar = new javax.swing.JRadioButton();
        txtFechaNac = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtSegNombre = new javax.swing.JTextField();
        lblSegNombre = new javax.swing.JLabel();
        lblPrimerAp = new javax.swing.JLabel();
        txtPrimerAp = new javax.swing.JTextField();
        lblSegAp = new javax.swing.JLabel();
        txtSegAp = new javax.swing.JTextField();
        lblTipoIden = new javax.swing.JLabel();
        cmbEquipo = new javax.swing.JComboBox<>();
        lblIden = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblTelef = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        cmbGenero = new javax.swing.JComboBox<>();
        lblPais = new javax.swing.JLabel();
        cmbPais = new javax.swing.JComboBox<>();
        lblProvin = new javax.swing.JLabel();
        cmbProvin = new javax.swing.JComboBox<>();
        lblCanton = new javax.swing.JLabel();
        cmbCanton = new javax.swing.JComboBox<>();
        lblFechaNac = new javax.swing.JLabel();
        cmbDistrito = new javax.swing.JComboBox<>();
        lblNumCamisa = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblAvatar = new javax.swing.JLabel();
        lblSelecFoto = new javax.swing.JLabel();
        btnCargarFoto = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        lblDistrito = new javax.swing.JLabel();
        cmbTipoIden = new javax.swing.JComboBox<>();
        lblEquipo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        spnNumCamisa = new javax.swing.JSpinner();
        lblDireccion = new javax.swing.JLabel();
        txtIden = new javax.swing.JFormattedTextField();
        txtTelef = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersonas = new javax.swing.JTable();
        txtareaEliminar = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));

        pnlAdminPersonas.setBackground(new java.awt.Color(86, 4, 44));
        pnlAdminPersonas.setMaximumSize(new java.awt.Dimension(1280, 720));
        pnlAdminPersonas.setMinimumSize(new java.awt.Dimension(1280, 720));
        pnlAdminPersonas.setPreferredSize(new java.awt.Dimension(1280, 720));
        pnlAdminPersonas.setLayout(null);

        lblAdmiPersonas.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        lblAdmiPersonas.setForeground(new java.awt.Color(255, 255, 255));
        lblAdmiPersonas.setText("Administrar Personas");
        pnlAdminPersonas.add(lblAdmiPersonas);
        lblAdmiPersonas.setBounds(100, 30, 521, 48);

        btnBack.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        btnBack.setContentAreaFilled(false);
        btnBack.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backPressed.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlAdminPersonas.add(btnBack);
        btnBack.setBounds(40, 40, 46, 40);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        pnlAdminPersonas.add(lblLogo);
        lblLogo.setBounds(1070, 10, 200, 125);

        cmbPersona.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jugador", "Cuerpo Técnico" }));
        cmbPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPersonaActionPerformed(evt);
            }
        });
        pnlAdminPersonas.add(cmbPersona);
        cmbPersona.setBounds(230, 110, 346, 31);

        lblPersona.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        lblPersona.setForeground(new java.awt.Color(255, 255, 255));
        lblPersona.setText("Tipo persona:");
        pnlAdminPersonas.add(lblPersona);
        lblPersona.setBounds(60, 110, 165, 32);

        btnGroupAdmiPersonas.add(rbtnEditar);
        rbtnEditar.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        rbtnEditar.setForeground(new java.awt.Color(255, 255, 255));
        rbtnEditar.setText("Editar");
        rbtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEditarActionPerformed(evt);
            }
        });
        pnlAdminPersonas.add(rbtnEditar);
        rbtnEditar.setBounds(770, 110, 100, 37);

        btnGroupAdmiPersonas.add(rbtnAgregar);
        rbtnAgregar.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        rbtnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        rbtnAgregar.setText("Agregar");
        rbtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAgregarActionPerformed(evt);
            }
        });
        pnlAdminPersonas.add(rbtnAgregar);
        rbtnAgregar.setBounds(610, 110, 150, 37);
        rbtnAgregar.setSelected(true);

        btnGroupAdmiPersonas.add(rbtnEliminar);
        rbtnEliminar.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        rbtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        rbtnEliminar.setText("Eliminar");
        rbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEliminarActionPerformed(evt);
            }
        });
        pnlAdminPersonas.add(rbtnEliminar);
        rbtnEliminar.setBounds(890, 110, 150, 37);
        pnlAdminPersonas.add(txtFechaNac);
        txtFechaNac.setBounds(290, 660, 230, 22);

        lblNombre.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre*");
        pnlAdminPersonas.add(lblNombre);
        lblNombre.setBounds(60, 170, 110, 40);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        pnlAdminPersonas.add(txtNombre);
        txtNombre.setBounds(290, 180, 230, 22);
        pnlAdminPersonas.add(txtSegNombre);
        txtSegNombre.setBounds(290, 240, 230, 22);

        lblSegNombre.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblSegNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblSegNombre.setText("Segundo nombre");
        pnlAdminPersonas.add(lblSegNombre);
        lblSegNombre.setBounds(60, 230, 210, 32);

        lblPrimerAp.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblPrimerAp.setForeground(new java.awt.Color(255, 255, 255));
        lblPrimerAp.setText("Primer apellido*");
        pnlAdminPersonas.add(lblPrimerAp);
        lblPrimerAp.setBounds(60, 290, 172, 32);

        txtPrimerAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimerApActionPerformed(evt);
            }
        });
        pnlAdminPersonas.add(txtPrimerAp);
        txtPrimerAp.setBounds(290, 300, 230, 22);

        lblSegAp.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblSegAp.setForeground(new java.awt.Color(255, 255, 255));
        lblSegAp.setText("Segundo apellido");
        pnlAdminPersonas.add(lblSegAp);
        lblSegAp.setBounds(60, 350, 210, 40);
        pnlAdminPersonas.add(txtSegAp);
        txtSegAp.setBounds(290, 360, 230, 22);

        lblTipoIden.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblTipoIden.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoIden.setText("Tipo Identificación*");
        pnlAdminPersonas.add(lblTipoIden);
        lblTipoIden.setBounds(60, 410, 210, 40);

        cmbEquipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEquipo.setMinimumSize(new java.awt.Dimension(80, 22));
        cmbEquipo.setPreferredSize(new java.awt.Dimension(80, 22));
        cmbEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEquipoActionPerformed(evt);
            }
        });
        pnlAdminPersonas.add(cmbEquipo);
        cmbEquipo.setBounds(290, 600, 230, 22);

        lblIden.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblIden.setForeground(new java.awt.Color(255, 255, 255));
        lblIden.setText("Identificación *");
        pnlAdminPersonas.add(lblIden);
        lblIden.setBounds(60, 470, 190, 40);

        lblCorreo.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setText("Correo*");
        pnlAdminPersonas.add(lblCorreo);
        lblCorreo.setBounds(60, 530, 110, 30);

        lblTelef.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblTelef.setForeground(new java.awt.Color(255, 255, 255));
        lblTelef.setText("Teléfono*");
        pnlAdminPersonas.add(lblTelef);
        lblTelef.setBounds(590, 170, 120, 40);

        lblGenero.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblGenero.setForeground(new java.awt.Color(255, 255, 255));
        lblGenero.setText("Género");
        pnlAdminPersonas.add(lblGenero);
        lblGenero.setBounds(590, 230, 110, 30);

        cmbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGeneroActionPerformed(evt);
            }
        });
        pnlAdminPersonas.add(cmbGenero);
        cmbGenero.setBounds(770, 240, 180, 22);

        lblPais.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblPais.setForeground(new java.awt.Color(255, 255, 255));
        lblPais.setText("País ");
        pnlAdminPersonas.add(lblPais);
        lblPais.setBounds(590, 290, 100, 30);

        cmbPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlAdminPersonas.add(cmbPais);
        cmbPais.setBounds(770, 300, 180, 22);

        lblProvin.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblProvin.setForeground(new java.awt.Color(255, 255, 255));
        lblProvin.setText("Provincia");
        pnlAdminPersonas.add(lblProvin);
        lblProvin.setBounds(590, 350, 120, 30);

        cmbProvin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlAdminPersonas.add(cmbProvin);
        cmbProvin.setBounds(770, 360, 180, 22);

        lblCanton.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblCanton.setForeground(new java.awt.Color(255, 255, 255));
        lblCanton.setText("Cantón");
        pnlAdminPersonas.add(lblCanton);
        lblCanton.setBounds(590, 410, 110, 30);

        cmbCanton.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlAdminPersonas.add(cmbCanton);
        cmbCanton.setBounds(770, 420, 180, 22);

        lblFechaNac.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblFechaNac.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaNac.setText("Fecha Nacimiento");
        pnlAdminPersonas.add(lblFechaNac);
        lblFechaNac.setBounds(60, 650, 200, 30);

        cmbDistrito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlAdminPersonas.add(cmbDistrito);
        cmbDistrito.setBounds(770, 480, 180, 22);

        lblNumCamisa.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblNumCamisa.setForeground(new java.awt.Color(255, 255, 255));
        lblNumCamisa.setText("Num Camisa*");
        pnlAdminPersonas.add(lblNumCamisa);
        lblNumCamisa.setBounds(1000, 180, 150, 40);
        pnlAdminPersonas.add(txtDireccion);
        txtDireccion.setBounds(590, 580, 360, 100);

        lblAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/avatar.png"))); // NOI18N
        lblAvatar.setAlignmentX(0.5F);
        lblAvatar.setMaximumSize(new java.awt.Dimension(180, 230));
        lblAvatar.setMinimumSize(new java.awt.Dimension(180, 230));
        lblAvatar.setPreferredSize(new java.awt.Dimension(180, 230));
        pnlAdminPersonas.add(lblAvatar);
        lblAvatar.setBounds(1050, 250, 180, 230);

        lblSelecFoto.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        lblSelecFoto.setForeground(new java.awt.Color(255, 255, 255));
        lblSelecFoto.setText("Seleccionar una fotografía");
        pnlAdminPersonas.add(lblSelecFoto);
        lblSelecFoto.setBounds(1040, 490, 200, 30);

        btnCargarFoto.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnCargarFoto.setText("Cargar foto");
        btnCargarFoto.setAlignmentY(0.0F);
        btnCargarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarFotoActionPerformed(evt);
            }
        });
        pnlAdminPersonas.add(btnCargarFoto);
        btnCargarFoto.setBounds(1080, 530, 120, 30);

        btnAceptar.setBackground(new java.awt.Color(86, 4, 44));
        btnAceptar.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorderPainted(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        pnlAdminPersonas.add(btnAceptar);
        btnAceptar.setBounds(1070, 650, 130, 40);

        lblDistrito.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblDistrito.setForeground(new java.awt.Color(255, 255, 255));
        lblDistrito.setText("Distrito");
        pnlAdminPersonas.add(lblDistrito);
        lblDistrito.setBounds(590, 470, 110, 30);

        cmbTipoIden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipoIden.setMinimumSize(new java.awt.Dimension(80, 22));
        cmbTipoIden.setPreferredSize(new java.awt.Dimension(80, 22));
        cmbTipoIden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoIdenActionPerformed(evt);
            }
        });
        pnlAdminPersonas.add(cmbTipoIden);
        cmbTipoIden.setBounds(290, 420, 230, 22);

        lblEquipo.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblEquipo.setForeground(new java.awt.Color(255, 255, 255));
        lblEquipo.setText("Equipo");
        pnlAdminPersonas.add(lblEquipo);
        lblEquipo.setBounds(60, 590, 110, 30);
        pnlAdminPersonas.add(txtCorreo);
        txtCorreo.setBounds(290, 540, 230, 22);

        spnNumCamisa.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        spnNumCamisa.setModel(new javax.swing.SpinnerNumberModel(1, 1, 999, 1));
        pnlAdminPersonas.add(spnNumCamisa);
        spnNumCamisa.setBounds(1160, 180, 90, 40);

        lblDireccion.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccion.setText("Dirección exacta:");
        pnlAdminPersonas.add(lblDireccion);
        lblDireccion.setBounds(590, 530, 190, 40);

        try {
            txtIden.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnlAdminPersonas.add(txtIden);
        txtIden.setBounds(290, 480, 230, 22);

        try {
            txtTelef.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnlAdminPersonas.add(txtTelef);
        txtTelef.setBounds(770, 180, 180, 22);

        tblPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPersonas);
        jScrollPane1.setVisible(false);

        pnlAdminPersonas.add(jScrollPane1);
        jScrollPane1.setBounds(80, 180, 580, 480);

        txtareaEliminar.setBackground(new java.awt.Color(86, 4, 44));
        txtareaEliminar.setColumns(20);
        txtareaEliminar.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        txtareaEliminar.setForeground(new java.awt.Color(255, 255, 255));
        txtareaEliminar.setRows(3);
        txtareaEliminar.setText("Seleccione una persona de la tabla de \nla izquierda para eliminarla. Presione  \n     aceptar para concluir la acción.");
        txtareaEliminar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(82, 4, 44)));
        txtareaEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtareaEliminar.setDisabledTextColor(new java.awt.Color(82, 4, 44));
        pnlAdminPersonas.add(txtareaEliminar);
        txtareaEliminar.setBounds(740, 310, 510, 150);
        txtareaEliminar.setEditable(false);
        txtareaEliminar.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdminPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdminPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   public boolean validarTextField(JTextField text){
       return text.getText().equals("");
   }
   
   public void esconderMostrarTodo(boolean flag){
       lblNombre.setVisible(flag);
       txtNombre.setVisible(flag);
       lblSegNombre.setVisible(flag);
       txtSegNombre.setVisible(flag);
       lblPrimerAp.setVisible(flag);
       txtPrimerAp.setVisible(flag);
       lblSegAp.setVisible(flag);
       txtSegAp.setVisible(flag);
       lblTipoIden.setVisible(flag);
       cmbTipoIden.setVisible(flag);
       lblIden.setVisible(flag);
       txtIden.setVisible(flag);
       lblCorreo.setVisible(flag);
       txtCorreo.setVisible(flag);
       
       lblEquipo.setVisible(flag);
       cmbEquipo.setVisible(flag);
       lblFechaNac.setVisible(flag);
       txtFechaNac.setVisible(flag);
       lblNumCamisa.setVisible(flag);
       spnNumCamisa.setVisible(flag);
       
       lblTelef.setVisible(flag);
       txtTelef.setVisible(flag);
       lblGenero.setVisible(flag);
       cmbGenero.setVisible(flag);
       lblPais.setVisible(flag);
       cmbPais.setVisible(flag);
       lblProvin.setVisible(flag);
       cmbProvin.setVisible(flag);
       lblCanton.setVisible(flag);
       cmbCanton.setVisible(flag);
       lblDistrito.setVisible(flag);
       cmbDistrito.setVisible(flag);
       lblDireccion.setVisible(flag);
       txtDireccion.setVisible(flag);
       
       lblAvatar.setVisible(flag);
       lblSelecFoto.setVisible(flag);
       btnCargarFoto.setVisible(flag);
       
       jScrollPane1.setVisible(!flag);
       txtareaEliminar.setVisible(!flag);
   }
   
   public void deshabilitarOpciones(boolean flag){
       lblFechaNac.setVisible(flag);
       txtFechaNac.setVisible(flag);
       lblNumCamisa.setVisible(flag);
       spnNumCamisa.setVisible(flag);
   }
   
   //GETTERS AND SETTERS

    public JButton getBtnAceptar() {
        return btnAceptar;
    }
   
    
   
   
    public String getTxtCorreo() {
        return txtCorreo.getText();
    }

    public void setTxtCorreo(JTextField txtCorreo) {
        this.txtCorreo = txtCorreo;
    }

    public String getTxtDireccion() {
        return txtDireccion.getText();
    }

    public void setTxtDireccion(JTextField txtDireccion) {
        this.txtDireccion = txtDireccion;
    }

    public String getTxtNombre() {
        return txtNombre.getText();
    }

    public void setTxtNombre(JTextField txtNombre) {
        this.txtNombre = txtNombre;
    }

    public String getTxtPrimerAp() {
        return txtPrimerAp.getText();
    }

    public void setTxtPrimerAp(JTextField txtPrimerAp) {
        this.txtPrimerAp = txtPrimerAp;
    }

    public JTextField getTxtSegAp() {
        return txtSegAp;
    }

    public void setTxtSegAp(JTextField txtSegAp) {
        this.txtSegAp = txtSegAp;
    }

    public String getTxtSegNombre() {
        return txtSegNombre.getText();
    }

    public void setTxtSegNombre(JTextField txtSegNombre) {
        this.txtSegNombre = txtSegNombre;
    }
   
   
   
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        JF_AdminOptions adminOptions = new JF_AdminOptions();
        adminOptions.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void rbtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAgregarActionPerformed
        esconderMostrarTodo(true);
        
        String tipoPersona = cmbPersona.getSelectedItem().toString();
        if("Cuerpo Técnico".equals(tipoPersona)){
           deshabilitarOpciones(false);
        }
    }//GEN-LAST:event_rbtnAgregarActionPerformed

    private void rbtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEditarActionPerformed
        esconderMostrarTodo(true);
        
        String tipoPersona = cmbPersona.getSelectedItem().toString();
        if("Cuerpo Técnico".equals(tipoPersona)){
           deshabilitarOpciones(false);
        }
    }//GEN-LAST:event_rbtnEditarActionPerformed

    private void cmbEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEquipoActionPerformed

    private void cmbGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGeneroActionPerformed

    private void btnCargarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarFotoActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void cmbTipoIdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoIdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoIdenActionPerformed

    private void txtPrimerApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimerApActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerApActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void cmbPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPersonaActionPerformed
       String tipoPersona = cmbPersona.getSelectedItem().toString();
        
       if((rbtnAgregar.isSelected() || rbtnEditar.isSelected()) && "Cuerpo Técnico".equals(tipoPersona)){
           deshabilitarOpciones(false);
       }
       if((rbtnAgregar.isSelected() || rbtnEditar.isSelected()) && "Jugador".equals(tipoPersona)){
           deshabilitarOpciones(true);
       }
    }//GEN-LAST:event_cmbPersonaActionPerformed

    private void rbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEliminarActionPerformed
        esconderMostrarTodo(false);
    }//GEN-LAST:event_rbtnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_AdminPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_AdminPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_AdminPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_AdminPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_AdminPerson().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCargarFoto;
    private javax.swing.ButtonGroup btnGroupAdmiPersonas;
    private javax.swing.JComboBox<String> cmbCanton;
    private javax.swing.JComboBox<String> cmbDistrito;
    private javax.swing.JComboBox<String> cmbEquipo;
    private javax.swing.JComboBox<String> cmbGenero;
    private javax.swing.JComboBox<String> cmbPais;
    private javax.swing.JComboBox<String> cmbPersona;
    private javax.swing.JComboBox<String> cmbProvin;
    private javax.swing.JComboBox<String> cmbTipoIden;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdmiPersonas;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblCanton;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDistrito;
    private javax.swing.JLabel lblEquipo;
    private javax.swing.JLabel lblFechaNac;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblIden;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumCamisa;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblPersona;
    private javax.swing.JLabel lblPrimerAp;
    private javax.swing.JLabel lblProvin;
    private javax.swing.JLabel lblSegAp;
    private javax.swing.JLabel lblSegNombre;
    private javax.swing.JLabel lblSelecFoto;
    private javax.swing.JLabel lblTelef;
    private javax.swing.JLabel lblTipoIden;
    private javax.swing.JPanel pnlAdminPersonas;
    private javax.swing.JRadioButton rbtnAgregar;
    private javax.swing.JRadioButton rbtnEditar;
    private javax.swing.JRadioButton rbtnEliminar;
    private javax.swing.JSpinner spnNumCamisa;
    private javax.swing.JTable tblPersonas;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFechaNac;
    private javax.swing.JFormattedTextField txtIden;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrimerAp;
    private javax.swing.JTextField txtSegAp;
    private javax.swing.JTextField txtSegNombre;
    private javax.swing.JFormattedTextField txtTelef;
    private javax.swing.JTextArea txtareaEliminar;
    // End of variables declaration//GEN-END:variables
}
