/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Isaac
 */
public class JF_EditAccount extends javax.swing.JFrame {

    /**
     * Creates new form JF_Stats
     */
    public JF_EditAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMyAccount = new javax.swing.JPanel();
        lblLogoMyAccount = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblMyAccountName1 = new javax.swing.JLabel();
        lblMyAccountName2 = new javax.swing.JLabel();
        lblMyAccountName4 = new javax.swing.JLabel();
        lblMyAccountName6 = new javax.swing.JLabel();
        lblMyAccountName10 = new javax.swing.JLabel();
        lblMyAccountName11 = new javax.swing.JLabel();
        lblMyAccountName12 = new javax.swing.JLabel();
        lblMyAccountName16 = new javax.swing.JLabel();
        lblMyAccountName17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1285, 752));

        panelMyAccount.setBackground(new java.awt.Color(86, 4, 44));
        panelMyAccount.setLayout(null);

        lblLogoMyAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        panelMyAccount.add(lblLogoMyAccount);
        lblLogoMyAccount.setBounds(1070, 10, 200, 130);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backPressed.png"))); // NOI18N
        panelMyAccount.add(jButton1);
        jButton1.setBounds(70, 80, 46, 40);

        lblMyAccountName1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 36)); // NOI18N
        lblMyAccountName1.setForeground(new java.awt.Color(255, 255, 255));
        lblMyAccountName1.setText("Bienvenido/a");
        panelMyAccount.add(lblMyAccountName1);
        lblMyAccountName1.setBounds(180, 80, 210, 48);

        lblMyAccountName2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 36)); // NOI18N
        lblMyAccountName2.setForeground(new java.awt.Color(255, 255, 255));
        lblMyAccountName2.setText("Isaac");
        panelMyAccount.add(lblMyAccountName2);
        lblMyAccountName2.setBounds(400, 80, 250, 50);

        lblMyAccountName4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblMyAccountName4.setForeground(new java.awt.Color(255, 255, 255));
        lblMyAccountName4.setText("Usuario:");
        panelMyAccount.add(lblMyAccountName4);
        lblMyAccountName4.setBounds(180, 170, 90, 32);

        lblMyAccountName6.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblMyAccountName6.setForeground(new java.awt.Color(255, 255, 255));
        lblMyAccountName6.setText("Contraseña:");
        panelMyAccount.add(lblMyAccountName6);
        lblMyAccountName6.setBounds(180, 230, 130, 32);

        lblMyAccountName10.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblMyAccountName10.setForeground(new java.awt.Color(255, 255, 255));
        lblMyAccountName10.setText("Nombre Completo:");
        panelMyAccount.add(lblMyAccountName10);
        lblMyAccountName10.setBounds(180, 290, 220, 32);

        lblMyAccountName11.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblMyAccountName11.setForeground(new java.awt.Color(255, 255, 255));
        lblMyAccountName11.setText("Género:");
        panelMyAccount.add(lblMyAccountName11);
        lblMyAccountName11.setBounds(180, 430, 220, 32);

        lblMyAccountName12.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblMyAccountName12.setForeground(new java.awt.Color(255, 255, 255));
        lblMyAccountName12.setText("Identificación:");
        panelMyAccount.add(lblMyAccountName12);
        lblMyAccountName12.setBounds(180, 360, 220, 32);

        lblMyAccountName16.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblMyAccountName16.setForeground(new java.awt.Color(255, 255, 255));
        lblMyAccountName16.setText("Email:");
        panelMyAccount.add(lblMyAccountName16);
        lblMyAccountName16.setBounds(180, 500, 220, 32);

        lblMyAccountName17.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblMyAccountName17.setForeground(new java.awt.Color(255, 255, 255));
        lblMyAccountName17.setText("Teléfono:");
        panelMyAccount.add(lblMyAccountName17);
        lblMyAccountName17.setBounds(180, 570, 220, 32);

        jButton2.setBackground(new java.awt.Color(86, 4, 44));
        jButton2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Editar perfil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelMyAccount.add(jButton2);
        jButton2.setBounds(960, 640, 150, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/avatar.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelMyAccount.add(jLabel1);
        jLabel1.setBounds(950, 250, 170, 230);

        jTextField1.setText("86480933");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        panelMyAccount.add(jTextField1);
        jTextField1.setBounds(520, 570, 280, 30);

        jTextField2.setText("Isaac4918");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        panelMyAccount.add(jTextField2);
        jTextField2.setBounds(520, 180, 280, 30);

        jTextField3.setText("ContraPrueba");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        panelMyAccount.add(jTextField3);
        jTextField3.setBounds(520, 240, 280, 30);

        jTextField4.setText("Isaac David Araya Solano");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        panelMyAccount.add(jTextField4);
        jTextField4.setBounds(520, 300, 280, 30);

        jTextField5.setText("305170939");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        panelMyAccount.add(jTextField5);
        jTextField5.setBounds(520, 360, 280, 30);

        jTextField6.setText("Masculino");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        panelMyAccount.add(jTextField6);
        jTextField6.setBounds(520, 430, 280, 30);

        jTextField7.setText("isaac4918@gmail.com");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        panelMyAccount.add(jTextField7);
        jTextField7.setBounds(520, 500, 280, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMyAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 1285, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMyAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_EditAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_EditAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_EditAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_EditAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_EditAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lblLogoMyAccount;
    private javax.swing.JLabel lblMyAccountName1;
    private javax.swing.JLabel lblMyAccountName10;
    private javax.swing.JLabel lblMyAccountName11;
    private javax.swing.JLabel lblMyAccountName12;
    private javax.swing.JLabel lblMyAccountName16;
    private javax.swing.JLabel lblMyAccountName17;
    private javax.swing.JLabel lblMyAccountName2;
    private javax.swing.JLabel lblMyAccountName4;
    private javax.swing.JLabel lblMyAccountName6;
    private javax.swing.JPanel panelMyAccount;
    // End of variables declaration//GEN-END:variables
}
