/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Isaac
 */
public class JF_GroupStats extends javax.swing.JFrame {

    /**
     * Creates new form JF_Stats
     */
    public JF_GroupStats() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        panelGroupStats = new javax.swing.JPanel();
        lblTeam2 = new javax.swing.JLabel();
        lblTeam1 = new javax.swing.JLabel();
        lblGoalsTeam1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTeam = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        lblLogoStats = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblTeam3 = new javax.swing.JLabel();
        lblTeam4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        mpTeam1 = new javax.swing.JLabel();
        wTeam1 = new javax.swing.JLabel();
        dTeam1 = new javax.swing.JLabel();
        LTeam1 = new javax.swing.JLabel();
        GFTeam1 = new javax.swing.JLabel();
        GATeam1 = new javax.swing.JLabel();
        diffTeam1 = new javax.swing.JLabel();
        fppTeam1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        mpTeam2 = new javax.swing.JLabel();
        wTeam2 = new javax.swing.JLabel();
        dTeam2 = new javax.swing.JLabel();
        LTeam2 = new javax.swing.JLabel();
        GFTeam2 = new javax.swing.JLabel();
        GATeam2 = new javax.swing.JLabel();
        diffTeam2 = new javax.swing.JLabel();
        fppTeam2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        mpTeam3 = new javax.swing.JLabel();
        wTeam3 = new javax.swing.JLabel();
        dTeam3 = new javax.swing.JLabel();
        LTeam3 = new javax.swing.JLabel();
        GFTeam3 = new javax.swing.JLabel();
        GATeam3 = new javax.swing.JLabel();
        diffTeam3 = new javax.swing.JLabel();
        fppTeam3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        mpTeam4 = new javax.swing.JLabel();
        wTeam4 = new javax.swing.JLabel();
        dTeam4 = new javax.swing.JLabel();
        LTeam4 = new javax.swing.JLabel();
        GFTeam4 = new javax.swing.JLabel();
        GATeam4 = new javax.swing.JLabel();
        diffTeam4 = new javax.swing.JLabel();
        fppTeam4 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1285, 752));

        panelGroupStats.setBackground(new java.awt.Color(86, 4, 44));
        panelGroupStats.setLayout(null);

        lblTeam2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblTeam2.setForeground(new java.awt.Color(255, 255, 255));
        lblTeam2.setText("Team2");
        panelGroupStats.add(lblTeam2);
        lblTeam2.setBounds(240, 410, 200, 32);

        lblTeam1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblTeam1.setForeground(new java.awt.Color(255, 255, 255));
        lblTeam1.setText("Team1");
        panelGroupStats.add(lblTeam1);
        lblTeam1.setBounds(240, 340, 200, 32);

        lblGoalsTeam1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 36)); // NOI18N
        lblGoalsTeam1.setForeground(new java.awt.Color(255, 255, 255));
        lblGoalsTeam1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGoalsTeam1.setText("Group X");
        panelGroupStats.add(lblGoalsTeam1);
        lblGoalsTeam1.setBounds(220, 170, 140, 70);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MP");
        panelGroupStats.add(jLabel2);
        jLabel2.setBounds(460, 290, 40, 20);

        lblTeam.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblTeam.setForeground(new java.awt.Color(255, 255, 255));
        lblTeam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTeam.setText("Team");
        panelGroupStats.add(lblTeam);
        lblTeam.setBounds(240, 290, 70, 20);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Pts");
        panelGroupStats.add(jLabel4);
        jLabel4.setBounds(960, 290, 30, 20);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("W");
        panelGroupStats.add(jLabel6);
        jLabel6.setBounds(530, 290, 30, 20);
        panelGroupStats.add(jSeparator2);
        jSeparator2.setBounds(220, 390, 870, 10);
        panelGroupStats.add(jSeparator3);
        jSeparator3.setBounds(220, 320, 870, 10);
        panelGroupStats.add(jSeparator4);
        jSeparator4.setBounds(220, 460, 870, 10);
        panelGroupStats.add(jSeparator5);
        jSeparator5.setBounds(220, 530, 870, 10);

        lblLogoStats.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        panelGroupStats.add(lblLogoStats);
        lblLogoStats.setBounds(1070, 10, 200, 130);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backPressed.png"))); // NOI18N
        panelGroupStats.add(jButton1);
        jButton1.setBounds(70, 80, 46, 40);

        lblTeam3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblTeam3.setForeground(new java.awt.Color(255, 255, 255));
        lblTeam3.setText("Team3");
        panelGroupStats.add(lblTeam3);
        lblTeam3.setBounds(240, 480, 190, 32);

        lblTeam4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblTeam4.setForeground(new java.awt.Color(255, 255, 255));
        lblTeam4.setText("Team4");
        panelGroupStats.add(lblTeam4);
        lblTeam4.setBounds(240, 550, 190, 32);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("D");
        panelGroupStats.add(jLabel5);
        jLabel5.setBounds(590, 290, 30, 20);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("L");
        panelGroupStats.add(jLabel7);
        jLabel7.setBounds(650, 290, 30, 20);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("GF");
        panelGroupStats.add(jLabel8);
        jLabel8.setBounds(710, 290, 30, 20);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("GA");
        panelGroupStats.add(jLabel9);
        jLabel9.setBounds(770, 290, 30, 20);

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("+/-");
        panelGroupStats.add(jLabel10);
        jLabel10.setBounds(830, 290, 30, 20);

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("FPP");
        panelGroupStats.add(jLabel11);
        jLabel11.setBounds(890, 290, 30, 20);

        mpTeam1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        mpTeam1.setForeground(new java.awt.Color(255, 255, 255));
        mpTeam1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mpTeam1.setText("0");
        panelGroupStats.add(mpTeam1);
        mpTeam1.setBounds(460, 350, 40, 20);

        wTeam1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        wTeam1.setForeground(new java.awt.Color(255, 255, 255));
        wTeam1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wTeam1.setText("0");
        panelGroupStats.add(wTeam1);
        wTeam1.setBounds(530, 350, 30, 20);

        dTeam1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        dTeam1.setForeground(new java.awt.Color(255, 255, 255));
        dTeam1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dTeam1.setText("0");
        panelGroupStats.add(dTeam1);
        dTeam1.setBounds(590, 350, 30, 20);

        LTeam1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        LTeam1.setForeground(new java.awt.Color(255, 255, 255));
        LTeam1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LTeam1.setText("0");
        panelGroupStats.add(LTeam1);
        LTeam1.setBounds(650, 350, 30, 20);

        GFTeam1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        GFTeam1.setForeground(new java.awt.Color(255, 255, 255));
        GFTeam1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GFTeam1.setText("0");
        panelGroupStats.add(GFTeam1);
        GFTeam1.setBounds(710, 350, 30, 20);

        GATeam1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        GATeam1.setForeground(new java.awt.Color(255, 255, 255));
        GATeam1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GATeam1.setText("0");
        panelGroupStats.add(GATeam1);
        GATeam1.setBounds(770, 350, 30, 20);

        diffTeam1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        diffTeam1.setForeground(new java.awt.Color(255, 255, 255));
        diffTeam1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        diffTeam1.setText("0");
        panelGroupStats.add(diffTeam1);
        diffTeam1.setBounds(830, 350, 30, 20);

        fppTeam1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        fppTeam1.setForeground(new java.awt.Color(255, 255, 255));
        fppTeam1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fppTeam1.setText("0");
        panelGroupStats.add(fppTeam1);
        fppTeam1.setBounds(890, 350, 30, 20);

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("0");
        panelGroupStats.add(jLabel19);
        jLabel19.setBounds(960, 350, 30, 20);

        mpTeam2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        mpTeam2.setForeground(new java.awt.Color(255, 255, 255));
        mpTeam2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mpTeam2.setText("0");
        panelGroupStats.add(mpTeam2);
        mpTeam2.setBounds(460, 420, 40, 20);

        wTeam2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        wTeam2.setForeground(new java.awt.Color(255, 255, 255));
        wTeam2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wTeam2.setText("0");
        panelGroupStats.add(wTeam2);
        wTeam2.setBounds(530, 420, 30, 20);

        dTeam2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        dTeam2.setForeground(new java.awt.Color(255, 255, 255));
        dTeam2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dTeam2.setText("0");
        panelGroupStats.add(dTeam2);
        dTeam2.setBounds(590, 420, 30, 20);

        LTeam2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        LTeam2.setForeground(new java.awt.Color(255, 255, 255));
        LTeam2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LTeam2.setText("0");
        panelGroupStats.add(LTeam2);
        LTeam2.setBounds(650, 420, 30, 20);

        GFTeam2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        GFTeam2.setForeground(new java.awt.Color(255, 255, 255));
        GFTeam2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GFTeam2.setText("0");
        panelGroupStats.add(GFTeam2);
        GFTeam2.setBounds(710, 420, 30, 20);

        GATeam2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        GATeam2.setForeground(new java.awt.Color(255, 255, 255));
        GATeam2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GATeam2.setText("0");
        panelGroupStats.add(GATeam2);
        GATeam2.setBounds(770, 420, 30, 20);

        diffTeam2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        diffTeam2.setForeground(new java.awt.Color(255, 255, 255));
        diffTeam2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        diffTeam2.setText("0");
        panelGroupStats.add(diffTeam2);
        diffTeam2.setBounds(830, 420, 30, 20);

        fppTeam2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        fppTeam2.setForeground(new java.awt.Color(255, 255, 255));
        fppTeam2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fppTeam2.setText("0");
        panelGroupStats.add(fppTeam2);
        fppTeam2.setBounds(890, 420, 30, 20);

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("0");
        panelGroupStats.add(jLabel20);
        jLabel20.setBounds(960, 420, 30, 20);

        mpTeam3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        mpTeam3.setForeground(new java.awt.Color(255, 255, 255));
        mpTeam3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mpTeam3.setText("0");
        panelGroupStats.add(mpTeam3);
        mpTeam3.setBounds(460, 490, 40, 20);

        wTeam3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        wTeam3.setForeground(new java.awt.Color(255, 255, 255));
        wTeam3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wTeam3.setText("0");
        panelGroupStats.add(wTeam3);
        wTeam3.setBounds(530, 490, 30, 20);

        dTeam3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        dTeam3.setForeground(new java.awt.Color(255, 255, 255));
        dTeam3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dTeam3.setText("0");
        panelGroupStats.add(dTeam3);
        dTeam3.setBounds(590, 490, 30, 20);

        LTeam3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        LTeam3.setForeground(new java.awt.Color(255, 255, 255));
        LTeam3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LTeam3.setText("0");
        panelGroupStats.add(LTeam3);
        LTeam3.setBounds(650, 490, 30, 20);

        GFTeam3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        GFTeam3.setForeground(new java.awt.Color(255, 255, 255));
        GFTeam3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GFTeam3.setText("0");
        panelGroupStats.add(GFTeam3);
        GFTeam3.setBounds(710, 490, 30, 20);

        GATeam3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        GATeam3.setForeground(new java.awt.Color(255, 255, 255));
        GATeam3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GATeam3.setText("0");
        panelGroupStats.add(GATeam3);
        GATeam3.setBounds(770, 490, 30, 20);

        diffTeam3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        diffTeam3.setForeground(new java.awt.Color(255, 255, 255));
        diffTeam3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        diffTeam3.setText("0");
        panelGroupStats.add(diffTeam3);
        diffTeam3.setBounds(830, 490, 30, 20);

        fppTeam3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        fppTeam3.setForeground(new java.awt.Color(255, 255, 255));
        fppTeam3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fppTeam3.setText("0");
        panelGroupStats.add(fppTeam3);
        fppTeam3.setBounds(890, 490, 30, 20);

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("0");
        panelGroupStats.add(jLabel21);
        jLabel21.setBounds(960, 490, 30, 20);

        mpTeam4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        mpTeam4.setForeground(new java.awt.Color(255, 255, 255));
        mpTeam4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mpTeam4.setText("0");
        panelGroupStats.add(mpTeam4);
        mpTeam4.setBounds(460, 560, 40, 20);

        wTeam4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        wTeam4.setForeground(new java.awt.Color(255, 255, 255));
        wTeam4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wTeam4.setText("0");
        panelGroupStats.add(wTeam4);
        wTeam4.setBounds(530, 560, 30, 20);

        dTeam4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        dTeam4.setForeground(new java.awt.Color(255, 255, 255));
        dTeam4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dTeam4.setText("0");
        panelGroupStats.add(dTeam4);
        dTeam4.setBounds(590, 560, 30, 20);

        LTeam4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        LTeam4.setForeground(new java.awt.Color(255, 255, 255));
        LTeam4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LTeam4.setText("0");
        panelGroupStats.add(LTeam4);
        LTeam4.setBounds(650, 560, 30, 20);

        GFTeam4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        GFTeam4.setForeground(new java.awt.Color(255, 255, 255));
        GFTeam4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GFTeam4.setText("0");
        panelGroupStats.add(GFTeam4);
        GFTeam4.setBounds(710, 560, 30, 20);

        GATeam4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        GATeam4.setForeground(new java.awt.Color(255, 255, 255));
        GATeam4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GATeam4.setText("0");
        panelGroupStats.add(GATeam4);
        GATeam4.setBounds(770, 560, 30, 20);

        diffTeam4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        diffTeam4.setForeground(new java.awt.Color(255, 255, 255));
        diffTeam4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        diffTeam4.setText("0");
        panelGroupStats.add(diffTeam4);
        diffTeam4.setBounds(830, 560, 30, 20);

        fppTeam4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        fppTeam4.setForeground(new java.awt.Color(255, 255, 255));
        fppTeam4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fppTeam4.setText("0");
        panelGroupStats.add(fppTeam4);
        fppTeam4.setBounds(890, 560, 30, 20);

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("0");
        panelGroupStats.add(jLabel22);
        jLabel22.setBounds(960, 560, 30, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGroupStats, javax.swing.GroupLayout.DEFAULT_SIZE, 1285, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGroupStats, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_GroupStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_GroupStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_GroupStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_GroupStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_GroupStats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GATeam1;
    private javax.swing.JLabel GATeam2;
    private javax.swing.JLabel GATeam3;
    private javax.swing.JLabel GATeam4;
    private javax.swing.JLabel GFTeam1;
    private javax.swing.JLabel GFTeam2;
    private javax.swing.JLabel GFTeam3;
    private javax.swing.JLabel GFTeam4;
    private javax.swing.JLabel LTeam1;
    private javax.swing.JLabel LTeam2;
    private javax.swing.JLabel LTeam3;
    private javax.swing.JLabel LTeam4;
    private javax.swing.JLabel dTeam1;
    private javax.swing.JLabel dTeam2;
    private javax.swing.JLabel dTeam3;
    private javax.swing.JLabel dTeam4;
    private javax.swing.JLabel diffTeam1;
    private javax.swing.JLabel diffTeam2;
    private javax.swing.JLabel diffTeam3;
    private javax.swing.JLabel diffTeam4;
    private javax.swing.JLabel fppTeam1;
    private javax.swing.JLabel fppTeam2;
    private javax.swing.JLabel fppTeam3;
    private javax.swing.JLabel fppTeam4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblGoalsTeam1;
    private javax.swing.JLabel lblLogoStats;
    private javax.swing.JLabel lblTeam;
    private javax.swing.JLabel lblTeam1;
    private javax.swing.JLabel lblTeam2;
    private javax.swing.JLabel lblTeam3;
    private javax.swing.JLabel lblTeam4;
    private javax.swing.JLabel mpTeam1;
    private javax.swing.JLabel mpTeam2;
    private javax.swing.JLabel mpTeam3;
    private javax.swing.JLabel mpTeam4;
    private javax.swing.JPanel panelGroupStats;
    private javax.swing.JLabel wTeam1;
    private javax.swing.JLabel wTeam2;
    private javax.swing.JLabel wTeam3;
    private javax.swing.JLabel wTeam4;
    // End of variables declaration//GEN-END:variables
}
