/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.JTable;

/**
 *
 * @author Isaac
 */
public class JF_GeneralStats extends javax.swing.JFrame {

    /**
     * Creates new form JF_GeneralStats
     */
    public JF_GeneralStats() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    
    
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        lblMyAccountName22 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lblLogoMyAccount = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblMyAccountName1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblStats8 = new javax.swing.JLabel();
        cmbAgeRange = new javax.swing.JComboBox<>();
        lblStats9 = new javax.swing.JLabel();
        lblStats10 = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox<>();
        lblStats11 = new javax.swing.JLabel();
        lblPlayerXAge = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblStats = new javax.swing.JLabel();
        lblStats1 = new javax.swing.JLabel();
        cmbNewsEvent = new javax.swing.JComboBox<>();
        lblStats2 = new javax.swing.JLabel();
        lblNewsEvent = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblStats3 = new javax.swing.JLabel();
        lblStats5 = new javax.swing.JLabel();
        cmbAuthor = new javax.swing.JComboBox<>();
        lblStats4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbReviewAverage = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblStats13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTopGoalkeepers = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        lblStats6 = new javax.swing.JLabel();
        cmbGroup = new javax.swing.JComboBox<>();
        lblStats7 = new javax.swing.JLabel();
        btnGroupTable = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        progressBarMatches = new javax.swing.JProgressBar();
        lblQuantityMatches = new javax.swing.JLabel();
        lblStats17 = new javax.swing.JLabel();
        lblStats14 = new javax.swing.JLabel();
        lblStats15 = new javax.swing.JLabel();
        lblStats16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblSavesXMatch = new javax.swing.JLabel();
        lblRedCards = new javax.swing.JLabel();
        lblGoalsXMatch = new javax.swing.JLabel();
        lblYellowCards = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblStats12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTopGoalPlayers = new javax.swing.JTable();

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("0.0");

        lblMyAccountName22.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        lblMyAccountName22.setForeground(new java.awt.Color(255, 255, 255));
        lblMyAccountName22.setText("Rango de edad:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1285, 752));

        jPanel1.setBackground(new java.awt.Color(86, 4, 44));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        lblLogoMyAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        jPanel1.add(lblLogoMyAccount);
        lblLogoMyAccount.setBounds(1080, 0, 200, 130);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backPressed.png"))); // NOI18N
        jPanel1.add(btnBack);
        btnBack.setBounds(60, 70, 46, 40);

        lblMyAccountName1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 48)); // NOI18N
        lblMyAccountName1.setForeground(new java.awt.Color(255, 255, 255));
        lblMyAccountName1.setText("Estadísticas");
        jPanel1.add(lblMyAccountName1);
        lblMyAccountName1.setBounds(140, 60, 250, 50);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        lblStats8.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 16)); // NOI18N
        lblStats8.setForeground(new java.awt.Color(255, 255, 255));
        lblStats8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStats8.setText("Total de jugadores por edad y género:");
        jPanel2.add(lblStats8);
        lblStats8.setBounds(0, 0, 310, 30);

        cmbAgeRange.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAgeRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAgeRangeActionPerformed(evt);
            }
        });
        jPanel2.add(cmbAgeRange);
        cmbAgeRange.setBounds(20, 50, 100, 30);

        lblStats9.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        lblStats9.setForeground(new java.awt.Color(255, 255, 255));
        lblStats9.setText("Rango de edad:");
        jPanel2.add(lblStats9);
        lblStats9.setBounds(20, 30, 110, 20);

        lblStats10.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        lblStats10.setForeground(new java.awt.Color(255, 255, 255));
        lblStats10.setText("Género:");
        jPanel2.add(lblStats10);
        lblStats10.setBounds(20, 80, 110, 20);

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGenderActionPerformed(evt);
            }
        });
        jPanel2.add(cmbGender);
        cmbGender.setBounds(20, 100, 100, 30);

        lblStats11.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        lblStats11.setForeground(new java.awt.Color(255, 255, 255));
        lblStats11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStats11.setText("Total:");
        jPanel2.add(lblStats11);
        lblStats11.setBounds(230, 40, 50, 30);

        lblPlayerXAge.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        lblPlayerXAge.setForeground(new java.awt.Color(255, 255, 255));
        lblPlayerXAge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPlayerXAge.setText("0.0");
        jPanel2.add(lblPlayerXAge);
        lblPlayerXAge.setBounds(170, 70, 110, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(90, 590, 310, 140);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(null);

        lblStats.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblStats.setForeground(new java.awt.Color(255, 255, 255));
        lblStats.setText("Total Noticias publicadas:");
        jPanel5.add(lblStats);
        lblStats.setBounds(10, 10, 220, 40);

        lblStats1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        lblStats1.setForeground(new java.awt.Color(255, 255, 255));
        lblStats1.setText("Seleccione el evento:");
        jPanel5.add(lblStats1);
        lblStats1.setBounds(40, 50, 140, 30);

        cmbNewsEvent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbNewsEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNewsEventActionPerformed(evt);
            }
        });
        jPanel5.add(cmbNewsEvent);
        cmbNewsEvent.setBounds(20, 90, 180, 30);

        lblStats2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        lblStats2.setForeground(new java.awt.Color(255, 255, 255));
        lblStats2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStats2.setText("Total:");
        jPanel5.add(lblStats2);
        lblStats2.setBounds(240, 50, 50, 30);

        lblNewsEvent.setFont(new java.awt.Font("Yu Gothic UI", 1, 30)); // NOI18N
        lblNewsEvent.setForeground(new java.awt.Color(255, 255, 255));
        lblNewsEvent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewsEvent.setText("0.0");
        jPanel5.add(lblNewsEvent);
        lblNewsEvent.setBounds(230, 80, 70, 50);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(90, 140, 310, 140);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel6.setOpaque(false);
        jPanel6.setLayout(null);

        lblStats3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblStats3.setForeground(new java.awt.Color(255, 255, 255));
        lblStats3.setText("Promedio de reviews por autor:");
        jPanel6.add(lblStats3);
        lblStats3.setBounds(10, 10, 280, 30);

        lblStats5.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        lblStats5.setForeground(new java.awt.Color(255, 255, 255));
        lblStats5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStats5.setText("Promedio:");
        jPanel6.add(lblStats5);
        lblStats5.setBounds(220, 50, 90, 30);

        cmbAuthor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAuthorActionPerformed(evt);
            }
        });
        jPanel6.add(cmbAuthor);
        cmbAuthor.setBounds(20, 90, 180, 30);

        lblStats4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        lblStats4.setForeground(new java.awt.Color(255, 255, 255));
        lblStats4.setText("Seleccione el autor:");
        jPanel6.add(lblStats4);
        lblStats4.setBounds(50, 50, 123, 30);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("0.0");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(60, 180, 70, 60);

        cmbReviewAverage.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        cmbReviewAverage.setForeground(new java.awt.Color(255, 255, 255));
        cmbReviewAverage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cmbReviewAverage.setText("0.0");
        jPanel6.add(cmbReviewAverage);
        cmbReviewAverage.setBounds(230, 80, 70, 50);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(90, 290, 310, 140);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        lblStats13.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblStats13.setForeground(new java.awt.Color(255, 255, 255));
        lblStats13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStats13.setText("Top porteros");
        jPanel3.add(lblStats13);
        lblStats13.setBounds(20, 10, 120, 40);

        tableTopGoalkeepers.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        tableTopGoalkeepers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Atajadas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableTopGoalkeepers);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(30, 60, 330, 210);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(810, 140, 390, 290);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(null);

        lblStats6.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblStats6.setForeground(new java.awt.Color(255, 255, 255));
        lblStats6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStats6.setText("Tabla de posiciones de los grupos:");
        jPanel4.add(lblStats6);
        lblStats6.setBounds(10, 10, 280, 40);

        cmbGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGroupActionPerformed(evt);
            }
        });
        jPanel4.add(cmbGroup);
        cmbGroup.setBounds(20, 90, 140, 30);

        lblStats7.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        lblStats7.setForeground(new java.awt.Color(255, 255, 255));
        lblStats7.setText("Seleccione el grupo:");
        jPanel4.add(lblStats7);
        lblStats7.setBounds(20, 60, 170, 20);

        btnGroupTable.setBackground(new java.awt.Color(86, 4, 44));
        btnGroupTable.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        btnGroupTable.setForeground(new java.awt.Color(255, 255, 255));
        btnGroupTable.setText("Ver tabla");
        btnGroupTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupTableActionPerformed(evt);
            }
        });
        jPanel4.add(btnGroupTable);
        btnGroupTable.setBounds(200, 90, 90, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(90, 440, 310, 140);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel7.setOpaque(false);
        jPanel7.setLayout(null);

        progressBarMatches.setForeground(new java.awt.Color(255, 204, 102));
        progressBarMatches.setValue(35);
        jPanel7.add(progressBarMatches);
        progressBarMatches.setBounds(30, 60, 730, 30);

        lblQuantityMatches.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblQuantityMatches.setForeground(new java.awt.Color(255, 255, 255));
        lblQuantityMatches.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuantityMatches.setText("35/100");
        jPanel7.add(lblQuantityMatches);
        lblQuantityMatches.setBounds(190, 10, 60, 40);

        lblStats17.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblStats17.setForeground(new java.awt.Color(255, 255, 255));
        lblStats17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStats17.setText("Atajadas por partido");
        jPanel7.add(lblStats17);
        lblStats17.setBounds(590, 130, 170, 40);

        lblStats14.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblStats14.setForeground(new java.awt.Color(255, 255, 255));
        lblStats14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStats14.setText("Partidos Jugados");
        jPanel7.add(lblStats14);
        lblStats14.setBounds(30, 10, 140, 40);

        lblStats15.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblStats15.setForeground(new java.awt.Color(255, 255, 255));
        lblStats15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStats15.setText("Goles por partido");
        jPanel7.add(lblStats15);
        lblStats15.setBounds(50, 130, 140, 40);

        lblStats16.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblStats16.setForeground(new java.awt.Color(255, 255, 255));
        lblStats16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStats16.setText("Tarjetas por partido");
        jPanel7.add(lblStats16);
        lblStats16.setBounds(310, 130, 170, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cards.png"))); // NOI18N
        jPanel7.add(jLabel1);
        jLabel1.setBounds(360, 180, 80, 70);

        lblSavesXMatch.setFont(new java.awt.Font("Yu Gothic UI", 1, 48)); // NOI18N
        lblSavesXMatch.setForeground(new java.awt.Color(255, 255, 255));
        lblSavesXMatch.setText("0.0");
        jPanel7.add(lblSavesXMatch);
        lblSavesXMatch.setBounds(650, 180, 70, 60);

        lblRedCards.setFont(new java.awt.Font("Yu Gothic UI", 1, 48)); // NOI18N
        lblRedCards.setForeground(new java.awt.Color(255, 255, 255));
        lblRedCards.setText("0.0");
        jPanel7.add(lblRedCards);
        lblRedCards.setBounds(260, 180, 70, 60);

        lblGoalsXMatch.setFont(new java.awt.Font("Yu Gothic UI", 1, 48)); // NOI18N
        lblGoalsXMatch.setForeground(new java.awt.Color(255, 255, 255));
        lblGoalsXMatch.setText("0.0");
        jPanel7.add(lblGoalsXMatch);
        lblGoalsXMatch.setBounds(80, 180, 70, 60);

        lblYellowCards.setFont(new java.awt.Font("Yu Gothic UI", 1, 48)); // NOI18N
        lblYellowCards.setForeground(new java.awt.Color(255, 255, 255));
        lblYellowCards.setText("0.0");
        jPanel7.add(lblYellowCards);
        lblYellowCards.setBounds(470, 180, 70, 60);

        jPanel1.add(jPanel7);
        jPanel7.setBounds(410, 440, 790, 290);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel8.setOpaque(false);
        jPanel8.setLayout(null);

        lblStats12.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblStats12.setForeground(new java.awt.Color(255, 255, 255));
        lblStats12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStats12.setText("Top goleadores");
        jPanel8.add(lblStats12);
        lblStats12.setBounds(20, 10, 140, 40);

        tableTopGoalPlayers.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        tableTopGoalPlayers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Goles"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableTopGoalPlayers.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(tableTopGoalPlayers);

        jPanel8.add(jScrollPane1);
        jScrollPane1.setBounds(30, 60, 330, 210);

        jPanel1.add(jPanel8);
        jPanel8.setBounds(410, 140, 390, 290);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1285, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnBack() {
        return btnBack;
    }

    public JButton getBtnGroupTable() {
        return btnGroupTable;
    }

    public JComboBox<String> getCmbAgeRange() {
        return cmbAgeRange;
    }

    public JComboBox<String> getCmbAuthor() {
        return cmbAuthor;
    }

    public JComboBox<String> getCmbGender() {
        return cmbGender;
    }

    public JComboBox<String> getCmbGroup() {
        return cmbGroup;
    }

    public JComboBox<String> getCmbNewsEvent() {
        return cmbNewsEvent;
    }

    public JLabel getCmbReviewAverage() {
        return cmbReviewAverage;
    }

    public JLabel getLblGoalsXMatch() {
        return lblGoalsXMatch;
    }

    public JLabel getLblLogoMyAccount() {
        return lblLogoMyAccount;
    }

    public JLabel getLblNewsEvent() {
        return lblNewsEvent;
    }

    public JLabel getLblPlayerXAge() {
        return lblPlayerXAge;
    }

    public JLabel getLblQuantityMatches() {
        return lblQuantityMatches;
    }

    public JLabel getLblRedCards() {
        return lblRedCards;
    }

    public JLabel getLblSavesXMatch() {
        return lblSavesXMatch;
    }

    public JLabel getLblYellowCards() {
        return lblYellowCards;
    }

    public JProgressBar getProgressBarMatches() {
        return progressBarMatches;
    }

    public JTable getTableTopGoalPlayers() {
        return tableTopGoalPlayers;
    }

    public JTable getTableTopGoalkeepers() {
        return tableTopGoalkeepers;
    }

    private void cmbAgeRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAgeRangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAgeRangeActionPerformed

    private void cmbNewsEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNewsEventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNewsEventActionPerformed

    private void cmbAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAuthorActionPerformed

    private void cmbGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGroupActionPerformed

    private void btnGroupTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGroupTableActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void cmbGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_GeneralStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_GeneralStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_GeneralStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_GeneralStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_GeneralStats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGroupTable;
    private javax.swing.JComboBox<String> cmbAgeRange;
    private javax.swing.JComboBox<String> cmbAuthor;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JComboBox<String> cmbGroup;
    private javax.swing.JComboBox<String> cmbNewsEvent;
    private javax.swing.JLabel cmbReviewAverage;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblGoalsXMatch;
    private javax.swing.JLabel lblLogoMyAccount;
    private javax.swing.JLabel lblMyAccountName1;
    private javax.swing.JLabel lblMyAccountName22;
    private javax.swing.JLabel lblNewsEvent;
    private javax.swing.JLabel lblPlayerXAge;
    private javax.swing.JLabel lblQuantityMatches;
    private javax.swing.JLabel lblRedCards;
    private javax.swing.JLabel lblSavesXMatch;
    private javax.swing.JLabel lblStats;
    private javax.swing.JLabel lblStats1;
    private javax.swing.JLabel lblStats10;
    private javax.swing.JLabel lblStats11;
    private javax.swing.JLabel lblStats12;
    private javax.swing.JLabel lblStats13;
    private javax.swing.JLabel lblStats14;
    private javax.swing.JLabel lblStats15;
    private javax.swing.JLabel lblStats16;
    private javax.swing.JLabel lblStats17;
    private javax.swing.JLabel lblStats2;
    private javax.swing.JLabel lblStats3;
    private javax.swing.JLabel lblStats4;
    private javax.swing.JLabel lblStats5;
    private javax.swing.JLabel lblStats6;
    private javax.swing.JLabel lblStats7;
    private javax.swing.JLabel lblStats8;
    private javax.swing.JLabel lblStats9;
    private javax.swing.JLabel lblYellowCards;
    private javax.swing.JProgressBar progressBarMatches;
    private javax.swing.JTable tableTopGoalPlayers;
    private javax.swing.JTable tableTopGoalkeepers;
    // End of variables declaration//GEN-END:variables
}
