/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Objects.MatchStats;

/**
 *
 * @author Isaac
 */
public class JF_MatchStats extends javax.swing.JFrame {

    /**
     * Creates new form JF_Stats
     */
    
    private MatchStats Team1 = new MatchStats();
    private MatchStats Team2 = new MatchStats();
    
    
    public JF_MatchStats() {
        initComponents();
    }
    
    
    public void loadInfoFrom(){
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelStats = new javax.swing.JPanel();
        lblTeam2 = new javax.swing.JLabel();
        lblTeam1 = new javax.swing.JLabel();
        lblGoalsTeam2 = new javax.swing.JLabel();
        lblGoalsTeam1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblSavesT2 = new javax.swing.JLabel();
        lblRedCardT1 = new javax.swing.JLabel();
        lblYellowCardT1 = new javax.swing.JLabel();
        lblOffsidesT1 = new javax.swing.JLabel();
        lblCornersT1 = new javax.swing.JLabel();
        lblSavesT1 = new javax.swing.JLabel();
        lblYellowCardT2 = new javax.swing.JLabel();
        lblRedCardT2 = new javax.swing.JLabel();
        lblOffsidesT2 = new javax.swing.JLabel();
        lblCornersT2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        lblLogoStats = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1285, 752));

        panelStats.setBackground(new java.awt.Color(86, 4, 44));
        panelStats.setLayout(null);

        lblTeam2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblTeam2.setForeground(new java.awt.Color(255, 255, 255));
        lblTeam2.setText("Team2");
        panelStats.add(lblTeam2);
        lblTeam2.setBounds(820, 80, 72, 32);

        lblTeam1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblTeam1.setForeground(new java.awt.Color(255, 255, 255));
        lblTeam1.setText("Team1");
        panelStats.add(lblTeam1);
        lblTeam1.setBounds(290, 80, 69, 32);

        lblGoalsTeam2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 60)); // NOI18N
        lblGoalsTeam2.setForeground(new java.awt.Color(255, 255, 255));
        lblGoalsTeam2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGoalsTeam2.setText("0");
        panelStats.add(lblGoalsTeam2);
        lblGoalsTeam2.setBounds(710, 60, 50, 70);

        lblGoalsTeam1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 60)); // NOI18N
        lblGoalsTeam1.setForeground(new java.awt.Color(255, 255, 255));
        lblGoalsTeam1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGoalsTeam1.setText("0");
        panelStats.add(lblGoalsTeam1);
        lblGoalsTeam1.setBounds(430, 60, 40, 70);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Saves");
        panelStats.add(jLabel2);
        jLabel2.setBounds(540, 390, 110, 20);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Yellow Cards");
        panelStats.add(jLabel3);
        jLabel3.setBounds(540, 490, 110, 20);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Red Cards");
        panelStats.add(jLabel4);
        jLabel4.setBounds(540, 590, 110, 20);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Offsides");
        panelStats.add(jLabel5);
        jLabel5.setBounds(540, 190, 110, 20);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Corners");
        panelStats.add(jLabel6);
        jLabel6.setBounds(540, 290, 110, 20);

        lblSavesT2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblSavesT2.setForeground(new java.awt.Color(255, 255, 255));
        lblSavesT2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSavesT2.setText("0");
        panelStats.add(lblSavesT2);
        lblSavesT2.setBounds(730, 390, 10, 25);

        lblRedCardT1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblRedCardT1.setForeground(new java.awt.Color(255, 255, 255));
        lblRedCardT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRedCardT1.setText("0");
        panelStats.add(lblRedCardT1);
        lblRedCardT1.setBounds(450, 590, 10, 25);

        lblYellowCardT1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblYellowCardT1.setForeground(new java.awt.Color(255, 255, 255));
        lblYellowCardT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblYellowCardT1.setText("0");
        panelStats.add(lblYellowCardT1);
        lblYellowCardT1.setBounds(450, 490, 10, 25);

        lblOffsidesT1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblOffsidesT1.setForeground(new java.awt.Color(255, 255, 255));
        lblOffsidesT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOffsidesT1.setText("0");
        panelStats.add(lblOffsidesT1);
        lblOffsidesT1.setBounds(450, 190, 10, 25);

        lblCornersT1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblCornersT1.setForeground(new java.awt.Color(255, 255, 255));
        lblCornersT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCornersT1.setText("0");
        panelStats.add(lblCornersT1);
        lblCornersT1.setBounds(450, 290, 10, 25);

        lblSavesT1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblSavesT1.setForeground(new java.awt.Color(255, 255, 255));
        lblSavesT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSavesT1.setText("0");
        panelStats.add(lblSavesT1);
        lblSavesT1.setBounds(450, 390, 10, 25);

        lblYellowCardT2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblYellowCardT2.setForeground(new java.awt.Color(255, 255, 255));
        lblYellowCardT2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblYellowCardT2.setText("0");
        panelStats.add(lblYellowCardT2);
        lblYellowCardT2.setBounds(730, 490, 10, 25);

        lblRedCardT2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblRedCardT2.setForeground(new java.awt.Color(255, 255, 255));
        lblRedCardT2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRedCardT2.setText("0");
        panelStats.add(lblRedCardT2);
        lblRedCardT2.setBounds(730, 590, 10, 25);

        lblOffsidesT2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblOffsidesT2.setForeground(new java.awt.Color(255, 255, 255));
        lblOffsidesT2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOffsidesT2.setText("0");
        panelStats.add(lblOffsidesT2);
        lblOffsidesT2.setBounds(730, 190, 10, 25);

        lblCornersT2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblCornersT2.setForeground(new java.awt.Color(255, 255, 255));
        lblCornersT2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCornersT2.setText("0");
        panelStats.add(lblCornersT2);
        lblCornersT2.setBounds(730, 290, 10, 25);
        panelStats.add(jSeparator1);
        jSeparator1.setBounds(410, 550, 380, 10);
        panelStats.add(jSeparator2);
        jSeparator2.setBounds(410, 250, 380, 10);
        panelStats.add(jSeparator3);
        jSeparator3.setBounds(410, 160, 380, 10);
        panelStats.add(jSeparator4);
        jSeparator4.setBounds(410, 350, 380, 10);
        panelStats.add(jSeparator5);
        jSeparator5.setBounds(410, 440, 380, 10);

        lblLogoStats.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        panelStats.add(lblLogoStats);
        lblLogoStats.setBounds(1070, 10, 200, 130);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backPressed.png"))); // NOI18N
        panelStats.add(jButton1);
        jButton1.setBounds(70, 80, 46, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelStats, javax.swing.GroupLayout.DEFAULT_SIZE, 1285, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelStats, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_MatchStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_MatchStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_MatchStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_MatchStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_MatchStats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblCornersT1;
    private javax.swing.JLabel lblCornersT2;
    private javax.swing.JLabel lblGoalsTeam1;
    private javax.swing.JLabel lblGoalsTeam2;
    private javax.swing.JLabel lblLogoStats;
    private javax.swing.JLabel lblOffsidesT1;
    private javax.swing.JLabel lblOffsidesT2;
    private javax.swing.JLabel lblRedCardT1;
    private javax.swing.JLabel lblRedCardT2;
    private javax.swing.JLabel lblSavesT1;
    private javax.swing.JLabel lblSavesT2;
    private javax.swing.JLabel lblTeam1;
    private javax.swing.JLabel lblTeam2;
    private javax.swing.JLabel lblYellowCardT1;
    private javax.swing.JLabel lblYellowCardT2;
    private javax.swing.JPanel panelStats;
    // End of variables declaration//GEN-END:variables
}
