/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Isaac
 */
public class JF_NewsWindow extends javax.swing.JFrame {

    /**
     * Creates new form JF_NewsWindow
     */
    public JF_NewsWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        lblNewsBody = new javax.swing.JLabel();
        lblRating = new javax.swing.JLabel();
        lblEstrella1 = new javax.swing.JLabel();
        lblEstrella2 = new javax.swing.JLabel();
        lblEstrella3 = new javax.swing.JLabel();
        lblEstrella4 = new javax.swing.JLabel();
        lblEstrella5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1292, 746));

        jPanel1.setBackground(new java.awt.Color(86, 4, 44));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TITLE");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 50, 150, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1090, 10, 190, 120);

        lblFoto.setOpaque(true);
        jPanel1.add(lblFoto);
        lblFoto.setBounds(50, 120, 420, 240);

        lblNewsBody.setText("jLabel4");
        lblNewsBody.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(lblNewsBody);
        lblNewsBody.setBounds(50, 380, 750, 340);

        lblRating.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 36)); // NOI18N
        lblRating.setForeground(new java.awt.Color(255, 255, 255));
        lblRating.setText("1.0");
        jPanel1.add(lblRating);
        lblRating.setBounds(750, 120, 50, 40);

        lblEstrella1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/estrella.png"))); // NOI18N
        jPanel1.add(lblEstrella1);
        lblEstrella1.setBounds(490, 120, 40, 40);

        lblEstrella2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/estrellaVacia.png"))); // NOI18N
        jPanel1.add(lblEstrella2);
        lblEstrella2.setBounds(540, 120, 40, 40);

        lblEstrella3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/estrellaVacia.png"))); // NOI18N
        jPanel1.add(lblEstrella3);
        lblEstrella3.setBounds(590, 120, 40, 40);

        lblEstrella4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/estrellaVacia.png"))); // NOI18N
        jPanel1.add(lblEstrella4);
        lblEstrella4.setBounds(640, 120, 40, 40);

        lblEstrella5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/estrellaVacia.png"))); // NOI18N
        jPanel1.add(lblEstrella5);
        lblEstrella5.setBounds(690, 120, 40, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1292, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_NewsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_NewsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_NewsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_NewsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_NewsWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEstrella1;
    private javax.swing.JLabel lblEstrella2;
    private javax.swing.JLabel lblEstrella3;
    private javax.swing.JLabel lblEstrella4;
    private javax.swing.JLabel lblEstrella5;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNewsBody;
    private javax.swing.JLabel lblRating;
    // End of variables declaration//GEN-END:variables
}
